server:
  port: 8080

self-feign:
  url:
    bili: https://v.api.aa1.cn
    local: http://localhost:8080

logging:
  config: classpath:logback-spring.xml
  file:
    name: logs/pencil-spring.log
  level:
    org.pencil.feign.decoder.FeignResultDecoder: DEBUG

spring:
  application:
    name: pencil-spring

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: org.pencil.test
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn