server:
  port: 8080

self-feign:
  url:
    bili: https://v.api.aa1.cn
    local: http://localhost:8080

logging:
  config: classpath:logback-spring.xml
  file:
    name: logs/pencil-spring.log
  level:
    org.pencil.feign.decoder.FeignResultDecoder: DEBUG

spring:
  application:
    name: pencil-spring

knife4j:
  enable: true
  openapi:
    title: Knife4j官方文档
    description: "pencil项目文档"
    email: pencil@gmail.com
    concat: pencil
    url: https://localhost:8080
    version: v4.0
    license: Apache 2.0
    license-url: https://stackoverflow.com/
    terms-of-service-url: https://stackoverflow.com/
    group:
      test1:
        group-name: 分组名称
        api-rule: package
        api-rule-resources:
          - org.pencil.test.controller